# Generated by Django 5.0.1 on 2024-07-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_comment_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='blog',
        ),
        migrations.AddField(
            model_name='comment',
            name='blog',
            field=models.ManyToManyField(to='main.blog'),
        ),
    ]
